# Generated by Django 4.1 on 2023-12-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_added',
            new_name='dateAdded',
        ),
    ]
